services:
  - type: web
    name: django-jwt-api
    env: python
    rootDir: backend            # ðŸ”´ VERY IMPORTANT â†’ tells Render manage.py is inside backend/
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.11.9
