services:
  - type: web
    name: django-jwt-api
    env: python
    rootDir: backend                   # ðŸ‘ˆ where manage.py is located
    buildCommand: |
      pip install -r ../requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PORT
        value: 8000
